import type { EventData } from "@/types/event";
import eventsCache from "@/data/events-cache.json";

// Static event data generated by scripts/fetch-eventbrite.mjs at build time.
// This JSON is bundled into the Worker — no filesystem or HTTP access at runtime.
const allEventsData = eventsCache as unknown as EventData[];

export async function getAllEvents(): Promise<EventData[]> {
  return allEventsData;
}

export async function getEventBySlug(slug: string): Promise<EventData | null> {
  return allEventsData.find((e) => e.slug === slug) ?? null;
}

export async function getUpcomingEvents(limit = 3): Promise<EventData[]> {
  const today = new Date().toISOString().slice(0, 10);
  return allEventsData
    .filter((e) => e.date >= today && e.status !== "cancelled")
    .sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0))
    .slice(0, limit);
}
